services:
  gatus:
    image: twinproduction/gatus:latest
    ports:
      - "8080:8080"
    environment:
      GATUS_CONFIG_BASE64: true
      GATUS_CONFIG: c3RvcmFnZToKICB0eXBlOiBzcWxpdGUKICBwYXRoOiAvZGF0YS9kYXRhLmRiCgplbmRwb2ludHM6CiAgLSBuYW1lOiBiYWNrLWVuZAogICAgZ3JvdXA6IGNvcmUKICAgIHVybDogImh0dHBzOi8vZXhhbXBsZS5vcmcvIgogICAgaW50ZXJ2YWw6IDVtCiAgICBjb25kaXRpb25zOgogICAgICAtICJbU1RBVFVTXSA9PSAyMDAiCiAgICAgIC0gIltDRVJUSUZJQ0FURV9FWFBJUkFUSU9OXSA+IDQ4aCIKCiAgLSBuYW1lOiBtb25pdG9yaW5nCiAgICBncm91cDogaW50ZXJuYWwKICAgIHVybDogImh0dHBzOi8vZXhhbXBsZS5vcmcvIgogICAgaW50ZXJ2YWw6IDVtCiAgICBjb25kaXRpb25zOgogICAgICAtICJbU1RBVFVTXSA9PSAyMDAiCgogIC0gbmFtZTogbmFzCiAgICBncm91cDogaW50ZXJuYWwKICAgIHVybDogImh0dHBzOi8vZXhhbXBsZS5vcmcvIgogICAgaW50ZXJ2YWw6IDVtCiAgICBjb25kaXRpb25zOgogICAgICAtICJbU1RBVFVTXSA9PSAyMDAiCgogIC0gbmFtZTogZXhhbXBsZS1kbnMtcXVlcnkKICAgIHVybDogIjguOC44LjgiICMgQWRkcmVzcyBvZiB0aGUgRE5TIHNlcnZlciB0byB1c2UKICAgIGludGVydmFsOiA1bQogICAgZG5zOgogICAgICBxdWVyeS1uYW1lOiAiZXhhbXBsZS5jb20iCiAgICAgIHF1ZXJ5LXR5cGU6ICJBIgogICAgY29uZGl0aW9uczoKICAgICAgLSAiW0JPRFldID09IDkzLjE4NC4yMTUuMTQiCiAgICAgIC0gIltETlNfUkNPREVdID09IE5PRVJST1IiCgogIC0gbmFtZTogaWNtcC1waW5nCiAgICB1cmw6ICJpY21wOi8vZXhhbXBsZS5vcmciCiAgICBpbnRlcnZhbDogMW0KICAgIGNvbmRpdGlvbnM6CiAgICAgIC0gIltDT05ORUNURURdID09IHRydWUiCg==

    volumes:
      - ./data:/data/
