metrics: true
services:
  - name: TwiNNatioN
    url: https://twinnation.org/health
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: GitHub
    url: https://api.github.com/healthz
    interval: 5m
    conditions:
      - "[STATUS] == 200"
  - name: Example
    url: https://example.com/
    conditions:
      - "[STATUS] == 200"