name: benchmark
on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository to checkout. Useful for benchmarking a fork. Format should be <owner>/<repository>."
        required: true
        default: ${{ github.repository }}
      ref:
        description: "Branch, tag or SHA to checkout"
        required: true
        default: "master"
jobs:
  build:
    name: benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/checkout@v3
      - name: Benchmark
        run: go test -bench=. ./storage/store
